{% set name = "makemake90" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85fca26bcb0b823732e37ffe8af13a7a608e9900fdcad29217a7d7fb904803bb

build:
  entry_points:
    - makemake90 = makemake90:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - makemake90
  commands:
    - pip check
    - makemake90
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janberges/makemake90
  summary: Generate Makefiles for modular Fortran programs
  license: 0BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
