{% set name = "makemake90" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2160d5bc2bf81557dc376676acdf458e52191373f1287e5ef4b67755bef53112

build:
  entry_points:
    - makemake90 = makemake90:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=2.7
    - flit-core >=3.4
    - pip
  run:
    - python >=2.7

test:
  imports:
    - makemake90
  commands:
    - pip check
    - makemake90
  requires:
    - pip

about:
  home: https://github.com/janberges/makemake90
  summary: Generate Makefiles for modular Fortran programs
  license: 0BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
