{% set name = "makemake90" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6e169bb13c130eaf212e9c13b118e93e672ecd6762458f7cfed04befc83538a

build:
  entry_points:
    - makemake90 = makemake90:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - makemake90
  commands:
    - pip check
    - makemake90
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janberges/makemake90
  summary: Generate Makefiles for modular Fortran programs
  license: 0BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janberges
